name: Test PAT Push Access

on:
  workflow_dispatch:  # Run manually from Actions tab

jobs:
  test-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make dummy file change
        run: |
          echo "Test run at $(date)" >> token_check.txt

      - name: Commit and push using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add token_check.txt
          git commit -m "Test commit using GH_PAT" || echo "No changes"
          git push
