name: Stock High Email Alert

on:
  schedule:
    - cron: "30 10 * * 1-5"  # 4:00 PM IST, Monday to Friday
  workflow_dispatch:

jobs:
  stock_alert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install yfinance

    - name: Run alert script
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: python main.py

